# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.12
      - image: docker.elastic.co/logstash/logstash:6.4.0
      - image: redis
      - image: nats
      - image: mongo
      - image: logstash

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
    links:
      - redis
      - nats
      - mongo
      - logstash
    depends_on:
      - redis
      - nats
      - mongo
      - logstash
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test
    nats:
      image: nats
      ports:
        - "4222:4222"

    mongo:
      image: circleci/mongo:3.4.4
      volumes:
        - ./db:/data/db
      ports:
        - "27017:27017"
    redis:
      image: redis
      ports:
        - "6379:6379"

    logstash:
      image: docker.elastic.co/logstash/logstash:6.4.0
      ports:
        - "9988:9988"

